# Linear Algebra

In [1]:
import matplotlib.pyplot as plt
import numpy as np


In [ ]:
v = np.array([5,5,3,7])
s = 4
v*s

In [ ]:
# Dotproduct of two vectors

v1 = np.array([5,3,2])
v2 = np.array([4,4,8])
np.vdot(v1,v2)

In [3]:
A = np.array([[4,0,5],[-1,3,2]])
B = np.array([[1,1,1],[3,5,7]])

A+B

array([[5, 1, 6],
       [2, 8, 9]])

In [5]:
A-2*B

array([[  2,  -2,   3],
       [ -7,  -7, -12]])

In [3]:
A = np.array([[5,1],[3,-2]])
B = np.array([[2,0],[4,3]])
print(A.dot(B))
print(B.dot(A))

[[14  3]
 [-2 -6]]
[[10  2]
 [29 -2]]
